echo off 
        
   
                                                           
REM This batch file displays the readme file.    

                                                                     
                                                                    
                                                        
                                                           
     
VPXHELP X (INDEX) README